
# build environment
FROM node:14 as build
MAINTAINER Gabriel Dissotti

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY yarn.lock ./

RUN yarn

COPY . ./

RUN yarn build

# production environment
FROM nginx:stable-alpine
MAINTAINER Gabriel Dissotti

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
