export * from './celsius.svg';
export * from './location.svg';
export * from './sun.svg';
export * from './raining.svg';
export * from './moon.svg';
export * from './clouds.svg';
export * from './snowing.svg';
export * from './thunderstorm.svg';
export * from './drizzle.svg';
export * from './others.svg'
