version: "3.8"

services:
    app:
        container_name: wheater-forecast-dev
        image: wheater-forecast-dev
        build:
            context: .
            target: development
        volumes:
            - ./src:/app/src
        ports:
            - 3000:3000
