FROM node:current-alpine as build
WORKDIR /app
ENV PATH="./node_modules/.bin:$PATH"
COPY package.json .
RUN yarn
COPY . .
RUN yarn run build
FROM nginx:stable-alpine
COPY --from=build /app/dist usr/share/nginx/html