version: '3'

services:
    weather-app-dev:
        build:
            context: .
            dockerfile: Dockerfile.prod
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 3000:3000
