version: "3.8"
services:
  app:
    container_name: challenge_charlie
    image: challenge_charlie
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
