# build environment

FROM node:current-alpine as build
WORKDIR /app
COPY package.json /app/package.json
RUN yarn
COPY . /app
RUN yarn run build

# production environment

FROM nginx:1.16.0-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
