version: "3.8"

services:
  app:
    container_name: charlie-challenge
    image: charlie-challenge
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000