version: "3.7"
services:
    react-app:
        container_name: challenge-charlie
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "3000:80"
        volumes:
            - ./src:/challenge-charlie/src
