FROM node:16.15.1-alpine3.15
WORKDIR /code
ENV PATH="./node_modules/.bin:$PATH"

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

COPY . .

CMD [ "npm", "run", "start" ]