version: "3.7"
services:
    app-prod:
        container_name: challenge-charlie-prod
        build:
            context: .
            dockerfile: Dockerfile-prod
        ports:
            - "8080:80"
