version: "3"

services:
    web-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3001:3000"
        volumes:
            - .:/src
        environment:
            - NODE_ENV=development
