// Generated by https://quicktype.io

import { OpenWeatherInstantCastResponse } from "./OpenWeatherInstantCastResponse";

export interface OpenWeather5DayCast {
    cod:     string;
    message: number;
    cnt:     number;
    list:    OpenWeatherInstantCastResponse[];
    city:    City;
}

export interface City {
    id:         number;
    name:       string;
    coord:      Coord;
    country:    string;
    population: number;
    timezone:   number;
    sunrise:    number;
    sunset:     number;
}

export interface Coord {
    lat: number;
    lon: number;
}