// Generated by https://quicktype.io

export interface OpenWeatherDirectGeocodingResponse {
    name:    string;
    lat:     number;
    lon:     number;
    country: string;
    state:   string;
    local_names: any;
}

export type OpenWeatherDirectGeocodingResponses = OpenWeatherDirectGeocodingResponse[];