// Generated by https://quicktype.io

export interface OpenWeatherCurrentCast {
    coord:      CurrentCastCoord;
    weather:    CurrentCastWeather[];
    base:       string;
    main:       CurrentCastMain;
    visibility: number;
    wind:       CurrentCastWind;
    clouds:     CurrentCastClouds;
    dt:         number;
    sys:        CurrentCastSys;
    timezone:   number;
    id:         number;
    name:       string;
    cod:        number;
}

export interface CurrentCastClouds {
    all: number;
}

export interface CurrentCastCoord {
    lon: number;
    lat: number;
}

export interface CurrentCastMain {
    temp:       number;
    feels_like: number;
    temp_min:   number;
    temp_max:   number;
    pressure:   number;
    humidity:   number;
}

export interface CurrentCastSys {
    type:    number;
    id:      number;
    country: string;
    sunrise: number;
    sunset:  number;
}

export interface CurrentCastWeather {
    id:          number;
    main:        string;
    description: string;
    icon:        string;
}

export interface CurrentCastWind {
    speed: number;
    deg:   number;
}
