export const FETCH_BACKGROUND = "FETCH_BACKGROUND";
export const FETCH_CURRENT_POSITION = "FETCH_CURRENT_POSITION";
export const FETCH_CURRENT_POSITION_FAIL = "FETCH_CURRENT_POSITION_FAIL";
export const FETCH_LOCATION = "FETCH_LOCATION";
export const FETCH_LOCATION_FAIL = "FETCH_LOCATION_FAIL";
export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";
