export default [
  'tornado',
  'tempestade tropical',
  'furacões',
  'trovoadas severas',
  'trovoadas',
  'chuva e neve misturadas',
  'nuvens de chuva e granizo',
  'neve e granizo mistos',
  'chuviscos gelados',
  'chuvisco',
  'chuva congelante',
  'chuvoso',
  'chuvoso',
  'rajadas de neve',
  'chuvas de neve fraca',
  'soprando neve',
  'neve',
  'granizo',
  'sleet',
  'pó',
  'nevoeiro',
  'neblina',
  'esfumaçado',
  'tempestuoso',
  'ventoso',
  'frio',
  'nublado',
  'mostly cloudy (noite)',
  'mostly cloudy (dia)',
  'parcialmente nublado (noite)',
  'parcialmente nublado (dia)',
  'claro (noite)',
  'ensolarado',
  'frio (noite)',
  'frio (dia)',
  'chuva misturada e granizo',
  'quente',
  'tempestades isoladas',
  'tempestades dispersas',
  'tempestades dispersas',
  'chuvoso espalhados',
  'neve pesada',
  'chuvoso de neve espalhados',
  'neve pesada',
  'parcialmente nublado',
  'trovões',
  'chuvoso de neve',
  'trovoadas isoladas',
];
