#Construição de Build
FROM node:10 as builder
RUN mkdir /usr/app
WORKDIR /usr/app
ENV PATH /usr/app/node_modules/.bin:$PATH
COPY package.json /usr/app/package.json
RUN npm install --silent
COPY . /usr/app
RUN npm run build

FROM nginx:1.13.9-alpine
COPY --from=builder /usr/app/build /usr/share/nginx/html
EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]