export const env = {
    BING_URL: process.env.REACT_APP_BING_URL,
    CORS_PROXY: process.env.REACT_APP_CORS_PROXY,
    OPEN_CAGE_API_KEY: process.env.REACT_APP_OPEN_CAGE_API_KEY,
    OPEN_CAGE_URL: process.env.REACT_APP_OPEN_CAGE_URL,
    OPEN_WEATHER_URL: process.env.REACT_APP_OPEN_WEATHER_URL,
    OPEN_WEATHER_API_KEY: process.env.REACT_APP_OPEN_WEATHER_API_KEY,
    POSITION_STACK_API_URL: process.env.REACT_APP_POSITION_STACK_API_URL,
    POSITION_STACK_API_KEY: process.env.REACT_APP_POSITION_STACK_API_KEY,
}
