export const PROXY_URL = 'http://localhost:9090/'
export const BING_IMAGE_URL_CACHEKEY = 'BING_IMAGE_URL'
export const BING_IMAGE_CACHEKEY = 'BING_IMAGE'
export const OPENCAGE_URL = 'https://api.opencagedata.com/geocode/v1/json'
export const OPENCAGE_APIKEY = 'c63386b4f77e46de817bdf94f552cddf'
