export const nominatimApiResponse = {
  place_id: 69059737,
  licence: 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  osm_type: 'node',
  osm_id: 6129129579,
  lat: '-22.9068196',
  lon: '-43.172804',
  display_name:
    'Praça do Expedicionário, Castelo, Centro, Zona Central do Rio de Janeiro, Rio de Janeiro, Região Geográfica Imediata do Rio de Janeiro, Região Metropolitana do Rio de Janeiro, Região Geográfica Intermediária do Rio de Janeiro, Rio de Janeiro, Southeast Region, 20030-080, Brazil',
  address: {
    amenity: 'Praça do Expedicionário',
    road: 'Praça do Expedicionário',
    quarter: 'Castelo',
    suburb: 'Centro',
    city_district: 'Zona Central do Rio de Janeiro',
    city: 'Rio de Janeiro',
    municipality: 'Região Geográfica Imediata do Rio de Janeiro',
    county: 'Região Metropolitana do Rio de Janeiro',
    state_district: 'Região Geográfica Intermediária do Rio de Janeiro',
    state: 'Rio de Janeiro',
    region: 'Southeast Region',
    postcode: '20030-080',
    country: 'Brazil',
    country_code: 'br',
  },
  boundingbox: ['-22.9068696', '-22.9067696', '-43.172854', '-43.172754'],
};
