export type Environment = {
    weatherForecast: {
        REDIS_LOCATION_DETAILS_BY_COORDINATES_HOST: string
        REDIS_LOCATION_DETAILS_BY_COORDINATES_PORT: number
        REDIS_LOCATION_DETAILS_BY_ADDRESS_HOST: string
        REDIS_LOCATION_DETAILS_BY_ADDRESS_PORT: number
        REDIS_LOCATION_WEATHER_FORECAST_BY_COORDINATES_HOST: string
        REDIS_LOCATION_WEATHER_FORECAST_BY_COORDINATES_PORT: number
        REDIS_PASSWORD: number
    }
}

export const defaultValue: Environment = {
    weatherForecast: {
        REDIS_LOCATION_DETAILS_BY_COORDINATES_HOST: "",
        REDIS_LOCATION_DETAILS_BY_COORDINATES_PORT: 0,
        REDIS_LOCATION_DETAILS_BY_ADDRESS_HOST: "",
        REDIS_LOCATION_DETAILS_BY_ADDRESS_PORT: 0,
        REDIS_LOCATION_WEATHER_FORECAST_BY_COORDINATES_HOST: "",
        REDIS_LOCATION_WEATHER_FORECAST_BY_COORDINATES_PORT: 0,
        REDIS_PASSWORD: 0
    }
}