export const LOAD_BING_IMAGE = 'LOAD_BING_IMAGE';
export const LOAD_WEATHER = 'LOAD_WEATHER';

export const UI = {
  NO_DATA: 'NO_DATA',
  LOADING_WEATHER: 'LOADING_WEATHER',
  SHOW_WEATHER: 'SHOW_WEATHER',
  UNDEFINED_WEATHER: 'UNDEFINED_WEATHER',
};
