export const LOAD_BACKGROUND_SUCCESS = 'LOAD_BACKGROUND_SUCCESS';
export const LOAD_LOCATION_WEATHER_SUCCESS = 'LOAD_LOCATION_WEATHER_SUCCESS';
export const CHANGE_TEMPERATURE_UNIT = 'CHANGE_TEMPERATURE_UNIT';
