export const LOAD_BACKGROUND_SUCCESS = 'LOAD_BACKGROUND_SUCCESS';
export const LOAD_LOCATION_WEATHER_SUCCESS = 'LOAD_LOCATION_WEATHER_SUCCESS';
export const CHANGE_TEMPERATURE_UNIT = 'CHANGE_TEMPERATURE_UNIT';
export const LOAD_CURRENT_LOCATION_WEATHER_SUCCESS =
    'LOAD_CURRENT_LOCATION_WEATHER_SUCCESS';
export const LOAD_CURRENT_LOCATION_WEATHER_FAIL =
    'LOAD_CURRENT_LOCATION_WEATHER_FAIL';
export const LOAD_LOCATION_NAME_SUGGESTION_SUCCESS =
    'LOAD_LOCATION_NAME_SUGGESTION_SUCCESS';
export const LOAD_LOCATION_NAME_SUGGESTION_FAIL =
    'LOAD_LOCATION_NAME_SUGGESTION_FAIL';
